### ISSUE TITLE
Created a phantom tune by fiddling with note values.

### ISSUE THREAD

**Issue by DavidGriffith** [macarc/PipeScore#13]
I made a new score (still named "My Tune") and entered notes from a previous doodle.  I then fiddled around with note values to figure out what time signature this earworm is in.  After a few minutes of this, when I changed a crotchet to a quaver, the page went blank - just a grey background.  Trying to load it from my scores page results in the same grey blank.

This is the phantom I created:

https://pipescore.web.app/pipescore/UhBkqQMSFVZjWbCtcszvskC98412/eCkMShqxcU0SXPA50Owb

This is what I got when I pressed "duplicate" for the one above:

https://pipescore.web.app/pipescore/UhBkqQMSFVZjWbCtcszvskC98412/oxQBwevGq2O6rS9s2uKL

I can't seem to trigger the bug again, so ll I can show you are these two phantom tunes.

**Comment by macarc** [comment]
These appear to load fine for me - I suspect it was fixed by 657a57d (when the first note's tied, it used to crash). The first note in that score is tied, so I guess that was what was causing the issue. Thanks for reporting it!
