### ISSUE TITLE
Multi-line headers break ImportBww regex

### ISSUE THREAD

**Issue by Jabrwock** [macarc/PipeScore#18]
The following headers break the regex in ImportBww because it is not expecting newlines between the brackets.
Regex ends up in a catastrophic backtracking.

BWW manual is ambiguous about newlines within a Mapping, although none of the examples include it.

Numerous samples from https://bagpipetunes.intertechnics.com/ include it. although not all BMWFC32 conversions do, so it's possible they were added after the fact by a text editor during formatting.

Recommend stripping out whitespace between the brackets prior to tokenizing mappings.

```
Bagpipe Reader:1.0

MIDINoteMappings,(54,56,58,59,61,63,
64,66,68,56,58,60,61,63,65,66,68,70,
55,57,59,60,62,64,65,67,69)

FrequencyMappings,(370,415,466,494,
554,622,659,740,831,415,466,523,554,
622,699,740,831,932,392,440,494,523,
587,659,699,784,880)

InstrumentMappings,(71,71,45,33,
1000,60,70)

GracenoteDurations,(20,40,30,50,
100,200,800,1200,250,250,250,500,200)

FontSizes,(90,100,88,80,250)

TuneFormat,(1,0,M,L,500,500,
500,500,P,0,0)

"Converted from Piob Mhor file format to Bagpipe Reader 1.0 format using
BMWFC32."
```

**Comment by macarc** [comment]
Great, thanks. I think probably the simplest way to solve this is to change the regexes to add optional whitespace between items in the lists.
