### ISSUE TITLE
Select closest note after deletion

### ISSUE THREAD

**Issue by benjaminelliot** [macarc/PipeScore#2]
When editing a score, you are able to delete a single note by selecting it and pressing the delete or backspace keys. However, once deleted there is no longer a selected note and if you want to delete the next nearest note, you will have to manually click it and press a delete key. See below:

![2022-10-17_12-48-28](https://user-images.githubusercontent.com/19875302/196236619-4b899877-74e6-46c5-a6e8-6fd32f9be41f.gif)

A user experience improvement that might be nice to add, would be highlighting the closest note after one is deleting while editing the score. It looks like you can use select + click to highlight multiple notes that you want to delete, but it could be nice for the user to also start deleting from a particular point in the score.

I wonder what your thoughts are on this.

**Comment by macarc** [comment]
Should be easy enough - using `Score::previousNote()` to find the previous note and selecting that before deleting the currently selected notes. Would this also happen if multiple notes are selected? I would say probably yes. If this is implemented it would also be good to do the same with Gracenote selection, i.e. deleting a single note in a gracenote would select the previous one.

If there are no previous notes, I guess it should select the next note.

Not sure if it would feel right going over a bar though (deleting the first note in a bar selects the last note of the previous bar). And especially not over staves. Bar exposes a `previousNote()` method as well; might be better using that.

**Comment by macarc** [comment]
Also, deleting a bar should have the same behaviour (selecting the previous/next bar on the same stave). I'm uncertain whether deleting staves should.

**Comment by macarc** [comment]
In that case, we'd have to add `previousNote()`/`nextNote()` to `Stave`.

After doing that, we should make sure that all of the uses of `Bar::previousNote()` and `Bar::nextNote()` are replaced with those.

e.g. some methods look like this:
```ts
for (const bar of score.bars()) bar.nextNote()
```
and should be replaced with this:
```ts
for (const stave of score.staves()) stave.nextNote()
```
It's probably cleaner overall if we do this anyway.

**Comment by macarc** [comment]
Trying this out, I think it works better if it only does this when deleting single notes, and only going to the previous note (*not* going to the next note if there's no other notes in the stave). This doesn't apply in gracenotes.

**Comment by benjaminelliot** [comment]
Excellent job, this works great!
