### ISSUE TITLE
"Your Scores" page is showing the type of tune as the title

### ISSUE THREAD

**Issue by DavidGriffith** [macarc/PipeScore#4]
When I'm logged in and looking at https://pipescore.web.app/scores, I see as my scores "Reel", and "March".  I should instead be seeing the names of the tunes.  This must have happened in the past three days or so because earlier than that, this wasn't a problem.

**Comment by macarc** [comment]
That is odd, as I haven't touched the code for the Scores page recently. Are these scores imported from BWW files? Were the scores showing their correction titles before?

**Comment by DavidGriffith** [comment]
These are tunes that I manually entered.  At first they were fine.  I have three scores.  The latest of which is called "Test" and is a "march".  The previous two are showing the strange behavior.  I just now created two new scores and the naming is correct.  While this might have been a random glitch, it would probably be a good idea to track down what happened.  Please login as me (dave@661.org).  If you need my password, please email me.

![pipescore-weird](https://github.com/macarc/PipeScore/assets/1289035/37f81232-2277-43b9-beb8-e82031d199eb)

**Comment by macarc** [comment]
Thank you for this. The title for the scores page is obtained by getting the first text box in the text box list for the score, so I suppose that list must be getting out of order somehow. I'm away this weekend but will look into this next week.

**Comment by macarc** [comment]
Hi, I believe I've now fixed the problem that was causing this (it occurred when dragging text boxes). I've gone through and fixed your scores too (since the fix didn't affect scores that already had the issue). Thanks for reporting it! Let me know if you're still experiencing the issue, or you run into anything else.
