### ISSUE TITLE
Export tunes

### ISSUE THREAD

**Issue by DavidGriffith** [macarc/PipeScore#7]
Another suggestion: add the ability to export tunes in some well-known formats (abc, bww, tex/bagpipetex, lilypond, musescore)

**Comment by macarc** [comment]
Exporting to BWW would be good as that can be imported into MuseScore. I am also more familiar with it since we support importing.

**Comment by macarc** [comment]
Going to close this now: we now support exporting to BWW - while the functionality is still a bit basic (doesn't support timings, or all gracenotes) it's there, and is being worked on. Thank you!
