### ISSUE TITLE
Slanted beams

### ISSUE THREAD

**Issue by DavidGriffith** [macarc/PipeScore#8]
Another suggestion: Automatically and maybe manually slant beams.

**Comment by macarc** [comment]
I initially implemented this (before ending up on flat beams): it is more complex than it first appears - the amount of slant depends on how far apart the notes are both horizontally and vertically, and I was not able to get something that looked nice for every different group of notes. Ultimately it was introducing a lot of complexity and simply looked better when everything was flat. I believe PiobMaster just does everything flat as well. I would maybe consider trying again but it is not high priority for me.
