### ISSUE TITLE
Three or four note birls?

### ISSUE THREAD

**Issue by DavidGriffith** [macarc/PipeScore#9]
Is there some means of controlling whether you get a three or four note birl?

**Comment by macarc** [comment]
Right now a 3-note birl is displayed when the previous note is a low A, otherwise a 4-note birl is shown. This seems the correct behaviour to me.

**Comment by DavidGriffith** [comment]
Given that the 3-note form sometimes appears when the previous note is not low A, I thought there should be an option for which one to use.  For instance, Dr. Peter L. Heineman' s "Highland Bagpipe Tutor Student Manual" (4th ed) on page 63 where he shows the three-note written without regard for the previous note and page 64 where he calls the four-note version the "great birl".

**Comment by macarc** [comment]
Perhaps I am misunderstanding - a 3 and 4 note birl are played exactly the same way, just notated differently. When you play a birl from a note other than A there will always be a short A before the birl, which is shown by the addition of an A in the birl, hence the 4 note birl. Notating a 3 note birl after anything other than an A is technically incorrect (in that it's not how it's played); however, some manuscripts are styled this way. I wouldn't want to support this - if people really want to write it stylistically (incorrectly) then they can manually delete the first A of the birl, which PipeScore supports doing.

There are also birls with G gracenotes, which have a different button.

**Comment by DavidGriffith** [comment]
Okay.  Somehow I missed the ability to delete individual notes from an ornamentation.

**Comment by macarc** [comment]
No worries. Do you think there's a way I could make it more obvious that it is possible to delete individual notes in embellishments?
